### ISSUE TITLE
How to use with scss?

### ISSUE THREAD

**Issue by sheerun** [shff/parcel-plugin-inliner#2]
I tried to use this plugin for my project that uses scss, but using scss requires doing an import in index.js file as so: `import './index.scss';`, I cannot simply link in index.html

Is there a way to use this plugin with scss?

**Comment by shff** [comment]
Hello, @sheerun! 

I am able to use it normally! I believe the problem happens because with recent versions of Parcel I have to run it using `--public-url .` for `inliner` to work!

Here are some examples:

https://gist.github.com/shff/8bf4606ecf1e3ee3ccee2a568d704c52
https://gist.github.com/shff/cdcaa31275c8ba9a8e2e230f445654a3

I'll see if I can find a way not to need it. I'll also add it to the README!

Let me know in case this doesn't work for you! You can re-open this issue if that's the case!
