### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by dhalucario** [shff/parcel-plugin-inliner#23]
I am currently trying to build an web application using Windows.

I did the following things:
```
npm install --save parcel-plugin-inliner
$env:INLINE_ASSETS = 'true'
$env:ENV = 'development'
parcel .\web\index.html
```
I checked out the `index.html` file and its still links to the `index.hash.css` and `index.hash.js` instead of inlining the content.

My environment is:
```
npm -v
7.14.0

node -v
v16.2.0

parcel --version
2.0.0-beta.3.1
```

**Comment by shff** [comment]
That's because Parcel Plugins that are prefixed with `parcel-plugin-` are not compatible with Parcel 2.0 anymore.

The only solution for this problem is rewriting this plugin and having a completely different name for it. I believe it would have to be `parcel-bundler-inline`.

I can't really modify this plugin, since some people still use Parcel 1. So it has to be completely new, from scratch.
